package uno.anahata.asi.tool;

import java.util.Map;
import java.util.concurrent.Callable;
import uno.anahata.asi.model.tool.java.JavaObjectToolkit;
import uno.anahata.asi.toolkit.Java;

/**
 * The base class for all Java code generated by the AI model.
 * It extends {@link ToolContext} to provide access to the chat environment
 * and implements {@link Callable} for execution.
 * 
 * @author anahata
 */
public abstract class AnahataTool extends ToolContext implements Callable<Object>{
    
    /**
     * Allows the model to programmatically set the "turns to keep" (retention) 
     * policy for the current tool call result.
     * 
     * @param turnsToKeep The number of turns to keep this result in context.
     */
    public void setTurnsToKeep(int turnsToKeep) {
        getResponse().setTurnsToKeep(turnsToKeep);
    }
    
}
