/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.tool;

import java.util.concurrent.Callable;

/**
 * The base class for Java code generated by the AI model.
 * Extending this class provides convenient access to logging, attachments,
 * and the full chat context via the helper methods inherited from {@link JavaToolkitInstance}.
 * 
 * @author anahata-gemini-pro-2.5
 */
public abstract class AnahataTool extends JavaToolkitInstance implements Callable<Object> {

    /**
     * The main entry point for the tool logic.
     * @return The result of the tool execution.
     * @throws Exception if an error occurs.
     */
    @Override
    public abstract Object call() throws Exception;
}
