/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.tool;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.Callable;
import uno.anahata.ai.chat.Chat;
import uno.anahata.ai.internal.TikaUtils;
import uno.anahata.ai.model.tool.java.JavaMethodTool;
import uno.anahata.ai.model.tool.java.JavaMethodToolCall;
import uno.anahata.ai.model.tool.java.JavaMethodToolResponse;
import uno.anahata.ai.resource.ResourceManager;

/**
 * The base class for Java code generated by the AI model.
 * Extending this class provides convenient access to logging, attachments,
 * and the full chat context via the helper methods inherited from {@link AnahataToolkit}.
 * 
 * @author anahata-gemini-pro-2.5
 */
public abstract class HandyToolStuff {
        /**
     * Gets the current tool response from the thread-local context.
     *
     * @return The current response.
     * @throws IllegalStateException if called outside the scope of a tool execution.
     */
    protected JavaMethodToolResponse getResponse() {
        JavaMethodToolResponse response = JavaMethodToolResponse.getCurrent();
        if (response == null) {
            throw new IllegalStateException("Cannot access ToolContext outside of a tool execution thread.");
        }
        return response;
    }

    /**
     * Convenience method to get the current tool call.
     * @return The current tool call.
     */
    protected JavaMethodToolCall getCall() {
        return getResponse().getCall();
    }

    /**
     * Convenience method to get the current tool definition.
     * @return The current tool.
     */
    protected JavaMethodTool getTool() {
        return getCall().getTool();
    }

    /**
     * Convenience method to get the application's ToolManager.
     * @return The ToolManager.
     */
    protected ToolManager getToolManager() {
        return getTool().getToolkit().getToolManager();
    }
    
    /**
     * Convenience method to get the application's ResourceManager.
     * @return The ResourceManager.
     */
    protected ResourceManager getResourceManager() {
        return getChat().getResourceManager();
    }

    /**
     * Convenience method to get the parent ToolManager session.
     * @return The ToolManager session.
     */
    protected Chat getChat() {
        return getToolManager().getChat();
    }

    /**
     * Adds a log message to the current tool's response.
     * @param message The log message.
     */
    protected void log(String message) {
        getResponse().addLog(message);
    }
    
    /**
     * Adds a log message to the current tool's response.
     * @param message The log message.
     */
    protected void error(String message) {
        getResponse().addError(message);
    }

    /**
     * Attaches a binary blob to the current tool's response.
     * @param data The binary data.
     * @param mimeType The MIME type of the data.
     */
    protected void addAttachment(byte[] data, String mimeType) {
        getResponse().addAttachment(data, mimeType);
    }
    
    /**
     * Convenience method to attach a file to the current tool's response.
     * The MIME type is detected automatically.
     * @param file The file to attach.
     * @throws IOException if the file cannot be read.
     */
    protected void addAttachment(File file) throws IOException {
        addAttachment(file.toPath());
    }
    
    /**
     * Convenience method to attach a file to the current tool's response.
     * The MIME type is detected automatically.
     * @param path The path to the file to attach.
     * @throws IOException if the file cannot be read.
     */
    protected void addAttachment(Path path) throws IOException {
        byte[] data = Files.readAllBytes(path);
        String mimeType;
        try {
            mimeType = TikaUtils.detectMimeType(path.toFile());
        } catch (Exception e) {
            throw new IOException("Failed to detect MIME type for " + path, e);
        }
        addAttachment(data, mimeType);
    }

}
