/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.model.core;

import java.util.List;

/**
 * A standardized, model-agnostic response received from an AI model provider.
 * This abstract class defines the contract for a response, allowing for
 * provider-specific implementations while maintaining a consistent API.
 *
 * @author anahata-gemini-pro-2.5
 * @param <T> The specific type of AbstractModelMessage this response contains.
 */
public abstract class Response<T extends AbstractModelMessage> {

    /**
     * Gets the list of candidate messages generated by the model.
     * @return A non-null, unmodifiable list of candidate messages of the specific type T.
     */
    public abstract List<T> getCandidates();

    /**
     * Gets the reason why the model stopped generating content.
     * @return The finish reason string, which may be null.
     */
    public abstract String getFinishReason();

    /**
     * Gets the number of tokens in the prompt.
     * @return The prompt token count.
     */
    public abstract int getPromptTokenCount();

    /**
     * Gets the total number of tokens for the entire interaction (prompt + all candidates).
     * @return The total token count.
     */
    public abstract int getTotalTokenCount();
}
