/*
 * Copyright 2025 Anahata.
 *
 * Licensed under the Anahata Software License (ASL) V2.0;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/pablo-anahata/anahata-ai-parent/blob/main/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Força Barça!
 */
package uno.anahata.ai.model.core;

import java.util.List;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;

/**
 * A standardized, model-agnostic response received from an AI model provider.
 * This class is designed to handle multiple candidate responses and associated metadata.
 * @author anahata-gemini-pro-2.5
 */
@Getter
@Builder
public class Response {
    /** A list of candidate messages generated by the model. */
    @NonNull
    private final List<AbstractMessage> candidates;

    /** The reason why the model stopped generating content. */
    private final String finishReason;

    /** The number of tokens in the prompt. */
    private final int promptTokenCount;

    /** The total number of tokens for the entire interaction (prompt + all candidates). */
    private final int totalTokenCount;
}
