/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.model.core;

import java.util.List;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;

/**
 * A standardized, model-agnostic response received from an AI model provider.
 * This class is designed to handle multiple candidate responses and associated metadata.
 *
 * @author anahata-gemini-pro-2.5
 */
@Getter
@Builder
public class Response {
    /** A list of candidate messages generated by the model. */
    @NonNull
    private final List<AbstractMessage> candidates;

    /** The reason why the model stopped generating content. */
    private final String finishReason;

    /** The number of tokens in the prompt. */
    private final int promptTokenCount;

    /** The total number of tokens for the entire interaction (prompt + all candidates). */
    private final int totalTokenCount;
}
