/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.model.core;

/**
 * Defines the role of the entity that created a message, providing a type-safe
 * way to distinguish between user, model, and tool messages.
 *
 * @author anahata-gemini-pro-2.5
 */
public enum Role {
    /** A message sent by the end-user. */
    USER,
    /** A message generated by the AI model. */
    MODEL,
    /** A message containing the results of a tool execution. */
    TOOL
}
