/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.openai;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import uno.anahata.asi.agi.message.AbstractMessage;
import uno.anahata.asi.agi.message.AbstractModelMessage;
import uno.anahata.asi.agi.message.AbstractPart;
import uno.anahata.asi.agi.message.BlobPart;
import uno.anahata.asi.agi.message.ModelTextPart;
import uno.anahata.asi.agi.message.Role;
import uno.anahata.asi.agi.message.TextPart;
import uno.anahata.asi.agi.message.ThoughtSignature;
import uno.anahata.asi.agi.tool.schema.SchemaProvider;
import uno.anahata.asi.agi.tool.spi.AbstractToolCall;
import uno.anahata.asi.agi.tool.spi.AbstractToolResponse;

/**
 * Pure content adapter for the OpenAI Responses API, strictly translating 
 * Anahata's domain model into the "Items" architecture.
 * 
 * <p>Supports text, images, audio, and generic files.</p>
 */
@Slf4j
@RequiredArgsConstructor
public class OpenAiItemAdapter {

    private static final ObjectMapper API_MAPPER = new ObjectMapper();
    private final AbstractMessage anahataMessage;
    private final boolean includePruned;
    private final String targetModelId;

    /**
     * Translates the message into a list of Responses API "Items".
     * 
     * @return A list of ObjectNodes representing the items.
     * @throws Exception on serialization errors.
     */
    public List<ObjectNode> toItems() throws Exception {
        List<ObjectNode> results = new ArrayList<>();
        
        if (anahataMessage.getRole() == Role.MODEL && anahataMessage instanceof AbstractModelMessage<?> modelMsg) {
            results.addAll(toModelTurnItems(modelMsg));
        } else {
            ObjectNode item = toUserOrSystemItem();
            if (item != null) results.add(item);
        }

        if (anahataMessage instanceof AbstractModelMessage<?> modelMsg) {
            results.addAll(toToolResponseItems(modelMsg));
        }
        
        return results;
    }

    private List<ObjectNode> toModelTurnItems(AbstractModelMessage<?> modelMsg) throws Exception {
        List<ObjectNode> items = new ArrayList<>();
        ObjectNode assistantItem = API_MAPPER.createObjectNode();
        assistantItem.put("type", "message");
        assistantItem.put("role", "assistant");
        ArrayNode contentArray = assistantItem.putArray("content");

        // Thought Loop: We only send encrypted reasoning back if this is an OpenAiMessage 
        // generated by the SAME model.
        boolean canSendSignature = anahataMessage instanceof OpenAiMessage 
                && Objects.equals(modelMsg.getModelId(), targetModelId);

        for (AbstractPart part : anahataMessage.getParts(true)) {
            if (part instanceof AbstractToolCall<?, ?> tc) {
                ObjectNode callItem = API_MAPPER.createObjectNode();
                callItem.put("type", "function_call");
                callItem.put("id", tc.getId());
                callItem.put("call_id", tc.getId());
                
                String fullName = tc.getToolName();
                int dotIdx = fullName.lastIndexOf(".");
                if (dotIdx > 0) {
                    callItem.put("namespace", fullName.substring(0, dotIdx));
                    callItem.put("name", fullName.substring(dotIdx + 1));
                } else {
                    callItem.put("name", fullName);
                }

                // Use SchemaProvider for Anahata DTO serialization (arguments)
                String argsJson = SchemaProvider.OBJECT_MAPPER.writeValueAsString(tc.getResponse().getExecutedArgs());
                callItem.put("arguments", argsJson);
                
                items.add(callItem);
            } else if (canSendSignature && part instanceof ThoughtSignature ts && ts.getThoughtSignature() != null) {
                // Injection: In stateless mode, we MUST send the encrypted reasoning back to OpenAI
                ObjectNode reasoningItem = API_MAPPER.createObjectNode();
                reasoningItem.put("type", "reasoning");
                reasoningItem.put("encrypted_content", new String(ts.getThoughtSignature()));
                items.add(reasoningItem);
                
                // Ghosting: If this part's text is just our placeholder, don't add it to the message item
                if (part instanceof TextPart tp && OpenAiMessage.ENCRYPTED_REASONING_PLACEHOLDER.equals(tp.getText())) {
                    continue;
                }
                addPartToContent(contentArray, part, "assistant");
            } else {
                addPartToContent(contentArray, part, "assistant");
            }
        }
        
        if (!contentArray.isEmpty()) {
            items.add(0, assistantItem);
        }
        return items;
    }

    private List<ObjectNode> toToolResponseItems(AbstractModelMessage<?> modelMsg) {
        List<AbstractToolResponse<?>> executedResponses = modelMsg.getToolResponses().stream()
                .filter(tr -> includePruned || !tr.getCall().isEffectivelyPruned())
                .filter(Objects::nonNull)
                .collect(Collectors.toList());
        
        List<ObjectNode> items = new ArrayList<>();
        for (AbstractToolResponse<?> tr : executedResponses) {
            ObjectNode responseItem = API_MAPPER.createObjectNode();
            responseItem.put("type", "function_call_output");
            responseItem.put("call_id", tr.getCall().getId());
            
            // Use SchemaProvider for Anahata DTO serialization (result object)
            String fullResponseJson = SchemaProvider.OBJECT_MAPPER.valueToTree(tr).toString();
            responseItem.put("output", fullResponseJson);
            items.add(responseItem);
        }
        return items;
    }

    private ObjectNode toUserOrSystemItem() {
        ObjectNode item = API_MAPPER.createObjectNode();
        item.put("type", "message");
        String role = anahataMessage.getRole() == Role.SYSTEM ? "system" : "user";
        item.put("role", role);
        ArrayNode contentArray = item.putArray("content");
        
        for (AbstractPart part : anahataMessage.getParts(true)) {
            addPartToContent(contentArray, part, role);
        }
        
        return contentArray.isEmpty() ? null : item;
    }

    private void addPartToContent(ArrayNode contentArray, AbstractPart part, String role) {
        if (part.isEffectivelyPruned() && !includePruned) {
            return;
        }

        // Critical Fix: Assistant items in history must use 'output_text'. 
        // User and System items must use 'input_text'.
        String typePrefix = "assistant".equals(role) ? "output_text" : "input_text";

        if (part instanceof TextPart tp) {
            contentArray.addObject().put("type", typePrefix).put("text", tp.getText());
        } else if (part instanceof ModelTextPart mtp) {
            // Reasoning parts (without signature) are sent as output_text in history
            contentArray.addObject().put("type", typePrefix).put("text", mtp.getText());
        } else if (part instanceof BlobPart bp) {
            String mime = bp.getMimeType();
            String b64 = Base64.getEncoder().encodeToString(bp.getData());
            
            if (mime.startsWith("image/")) {
                ObjectNode node = contentArray.addObject();
                node.put("type", "input_image");
                node.putObject("input_image").put("data", b64).put("format", mime.substring(6));
            } else if (mime.startsWith("audio/")) {
                ObjectNode node = contentArray.addObject();
                node.put("type", "input_audio");
                node.putObject("audio").put("data", b64).put("format", mime.substring(6));
            } else {
                // Generic file support (PDF, XML, etc.)
                ObjectNode node = contentArray.addObject();
                node.put("type", "input_file");
                node.put("file_data", b64);
                node.put("mime_type", mime);
                if (bp.getSourcePath() != null) {
                    node.put("filename", bp.getSourcePath().getFileName().toString());
                }
            }
        }
    }
}
