/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.model.tool;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.exception.ExceptionUtils;
import uno.anahata.asi.internal.TextUtils;
import uno.anahata.asi.model.core.AbstractPart;

/**
 * Represents the response of a tool call, designed for deferred execution.
 * The fields are populated by the {@link #execute()} method.
 * 
 * @author anahata-gemini-pro-2.5
 * @param <C> The specific type of the Call this response is for.
 */
@Getter
@Setter
public abstract class AbstractToolResponse<C extends AbstractToolCall<?, ?>> extends AbstractPart {
    /** The final status of the invocation after execution. */
    @Setter(lombok.AccessLevel.NONE)
    private ToolExecutionStatus status;

    /** The result of the invocation if it succeeded, otherwise {@code null}. */
    private Object result;

    /** A descriptive error message if the tool failed or was rejected. */
    private String error;

    /** The time taken to execute the method, in milliseconds. */
    private long executionTimeMillis;
    
    @Schema(description = "the name of thread that executed this tool")
    private String threadName;
    
    @JsonIgnore
    private transient Thread thread;
    
    /** A list of log messages captured during the tool's execution. */
    private final List<String> logs = new ArrayList<>();
    
    /** A list of attachments (e.g., images, files) generated by the tool. */
    private final List<ToolResponseAttachment> attachments = new ArrayList<>();
    
    /** Optional feedback from the user if the tool execution was prompted. */
    private String userFeedback;

    public AbstractToolResponse(AbstractToolCall<?, ?> call) {
        super(call.getMessage().getToolMessage());
    }
    
    /**
     * Sets the status of the tool execution and fires a property change event.
     * 
     * @param status The new status.
     */
    public void setStatus(ToolExecutionStatus status) {
        ToolExecutionStatus oldStatus = this.status;
        this.status = status;
        getPropertyChangeSupport().firePropertyChange("status", oldStatus, status);
    }
    
    /**
     * Gets the name of the tool that was invoked.
     * @return The tool's name.
     */
    public String getToolName() {
        return getCall().getToolName();
    }
    
    /**
     * Gets the original invocation request that this result corresponds to.
     * @return The originating tool call.
     */
    public abstract C getCall();
    
    /**
     * Executes the tool logic. This method is responsible for populating
     * the status, result, error, and executionTimeMillis fields.
     */
    public abstract void execute();

    /**
     * Stops the tool execution if it is currently running.
     */
    public abstract void stop();

    /**
     * Rejects the tool call before execution, setting the status to NOT_EXECUTED.
     * @param reason The reason for the rejection.
     */
    public void reject(String reason) {
        setStatus(ToolExecutionStatus.NOT_EXECUTED);
        setError(reason);
    }
    
    /**
     * Sets the running thread and updates the thread name.
     * 
     * @param thread the executing thread.
     */
    public void setThread(Thread thread) {
        if (thread != null) {
            this.threadName = thread.getName();
            getPropertyChangeSupport().firePropertyChange("threadName", null, threadName);
        } else {
            this.threadName = null;
        }
        this.thread = thread;
        getPropertyChangeSupport().firePropertyChange("thread", null, thread);
    }
    
    /**
     * Resets the response to its initial state, clearing results, errors, logs, and attachments.
     */
    public void reset() {
        setStatus(ToolExecutionStatus.NOT_EXECUTED);
        setResult(null);
        setError(null);
        setThread(null);
        setExecutionTimeMillis(0);
        clearLogs();
        this.attachments.clear();
        getPropertyChangeSupport().firePropertyChange("attachments", null, attachments);
    }

    /**
     * Adds a log message to this response, which can be displayed to the user.
     * @param message The log message.
     */
    public void addLog(String message) {
        this.logs.add(message);
        getPropertyChangeSupport().firePropertyChange("logs", null, logs);
    }
    
    /**
     * Converts a exception to a string and adds it to the error field.
     * 
     * @param t The exception to add.
     */
    public void addError(Throwable t) {
        addError(ExceptionUtils.getStackTrace(t));
    }
    /**
     * Adds a log message to this response, which can be displayed to the user.
     * @param error The error message to add.
     */
    public void addError(String error) {
        if (this.error == null) {
            this.error = error;
        } else {
            this.error = "\n" + error;
        }
        getPropertyChangeSupport().firePropertyChange("error", null, this.error);
    }
    
    /**
     * Attaches a binary blob to this response.
     * @param data The binary data.
     * @param mimeType The MIME type of the data.
     */
    public void addAttachment(byte[] data, String mimeType) {
        this.attachments.add(new ToolResponseAttachment(data, mimeType));
        getPropertyChangeSupport().firePropertyChange("attachments", null, attachments);
    }

    /**
     * Removes an attachment from this response.
     * @param attachment The attachment to remove.
     */
    public void removeAttachment(ToolResponseAttachment attachment) {
        if (this.attachments.remove(attachment)) {
            getPropertyChangeSupport().firePropertyChange("attachments", null, attachments);
        }
    }
    
    /**
     * Gets an unmodifiable view of the attachments.
     * @return The list of attachments.
     */
    public List<ToolResponseAttachment> getAttachments() {
        return Collections.unmodifiableList(attachments);
    }

    /**
     * Clears any log messages captured during execution.
     */
    public void clearLogs() {
        this.logs.clear();
        getPropertyChangeSupport().firePropertyChange("logs", null, logs);
    }
    
    @Override
    protected int getDefaultTurnsToKeep() {
        return getChatConfig().getDefaultToolTurnsToKeep();
    }
    
    @Override
    public String asText() {
        return String.format("[%s] %s", status, result != null ? TextUtils.formatValue(result) : (error != null ? error : ""));
    }
}
