/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.model.tool;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.Getter;
import lombok.Setter;
import uno.anahata.ai.model.core.AbstractMessage;
import uno.anahata.ai.model.core.AbstractPart;
import uno.anahata.ai.model.core.BlobPart;
import uno.anahata.ai.model.core.AbstractModelMessage;
import uno.anahata.ai.model.core.TextPart;

/**
 * Represents the response of a tool call, designed for deferred execution.
 * The fields are populated by the {@link #execute()} method.
 * 
 * @author anahata-gemini-pro-2.5
 * @param <C> The specific type of the Call this response is for.
 */
@Getter
public abstract class AbstractToolResponse<C extends AbstractToolCall> extends AbstractPart {
    /** The final status of the invocation after execution. */
    @Setter
    private ToolExecutionStatus status;

    /** The result of the invocation if it succeeded, otherwise {@code null}. */
    @Setter
    private Object result;

    /** A descriptive error message if the tool failed or was rejected. */
    @Setter
    private String error;

    /** The time taken to execute the method, in milliseconds. */
    @Setter
    private long executionTimeMillis;
    
    /** A list of log messages captured during the tool's execution. */
    private final List<String> logs = new ArrayList<>();
    
    /** A list of attachments (e.g., images, files) generated by the tool. */
    private final List<AbstractPart> attachments = new ArrayList<>();
    
    /** Optional feedback from the user if the tool execution was prompted. */
    @Setter
    private String userFeedback;

    public AbstractToolResponse(AbstractToolCall call) {
        super(call.getMessage().getToolMessage());
    }
    
    /**
     * Gets the original invocation request that this result corresponds to.
     * @return The originating tool call.
     */
    public abstract C getCall();
    
    /**
     * Executes the tool logic. This method is responsible for populating
     * the status, result, error, and executionTimeMillis fields.
     */
    public abstract void execute();

    /**
     * Rejects the tool call before execution, setting the status to NOT_EXECUTED.
     * @param reason The reason for the rejection.
     */
    public void reject(String reason) {
        setStatus(ToolExecutionStatus.NOT_EXECUTED);
        setError(reason);
    }

    /**
     * Adds a log message to this response, which can be displayed to the user.
     * @param message The log message.
     */
    public void addLog(String message) {
        this.logs.add(message);
    }
    
    /**
     * Attaches a binary part (e.g., an image) to this response.
     * @param attachment The BlobPart to attach.
     */
    public void addAttachment(BlobPart attachment) {
        this.attachments.add(attachment);
    }
    
    /**
     * Attaches a text part (e.g., a code snippet) to this response.
     * @param attachment The TextPart to attach.
     */
    public void addAttachment(TextPart attachment) {
        this.attachments.add(attachment);
    }
    
    /**
     * Gets an unmodifiable view of the attachments.
     * @return The list of attachments.
     */
    public List<AbstractPart> getAttachments() {
        return Collections.unmodifiableList(attachments);
    }

    /**
     * Clears any log messages captured during execution.
     */
    public void clearLogs() {
        this.logs.clear();
    }
    
    @Override
    protected int getDefaultTurnsToKeep() {
        return getChatConfig().getDefaultToolTurnsToKeep();
    }
    
    @Override
    public String asText() {
        return "[Tool Response: " + getStatus() + ", Result: " + getResult() + "]";
    }
}
