name: anahata-asi-desktop
base: core24
version: '1.1.12'
summary: The Stateful, Air-Gapped Java ASI Container
description: |
  Anahata ASI Desktop is a stateful, air-gapped Java ASI container with 
  deep hardware integration, session passivation, and complete observability.
  Pioneering Artificial Super Intelligence on the shoulders of Java giants.
website: https://asi.anahata.uno

grade: stable
confinement: classic

apps:
  anahata-asi-desktop:
    command: bin/Anahata-ASI-Desktop

parts:
  desktop-app:
    plugin: dump
    source: dist/Anahata-ASI-Desktop
