/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.model.core;

import lombok.Getter;
import lombok.Setter;


/**
 * A concrete {@link TextPart} implementation for text content generated by the model,
 * including internal thought process details.
 *
 * @author anahata-gemini-pro-2.5
 */
@Getter
@Setter
public class ModelTextPart extends TextPart implements ThoughtSignature {
    private byte[] thoughtSignature;
    private boolean thought;

    /**
     * Constructs a new ModelTextPart.
     *
     * @param message The model message this part belongs to. Must be a {@link AbstractModelMessage}.
     * @param text The text content.
     * @param thoughtSignature The signature of the thought process as a byte array.
     * @param thought Whether this part represents a thought process.
     */
    public ModelTextPart(AbstractModelMessage message, String text, byte[] thoughtSignature, boolean thought) {
        super(message, text);
        this.thoughtSignature = thoughtSignature;
        this.thought = thought;
    }

    @Override
    public boolean isThought() {
        return thought;
    }
}
