/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.model.core;

import lombok.Getter;
import lombok.Setter;
import uno.anahata.asi.chat.ChatConfig;


/**
 * A concrete {@link TextPart} implementation for text content generated by the model,
 * including internal thought process details.
 *
 * @author anahata
 */
@Getter
@Setter
public class ModelTextPart extends TextPart implements ThoughtSignature {
    private byte[] thoughtSignature;
    private boolean thought;

    /**
     * Constructs a new ModelTextPart.
     *
     * @param message The model message this part belongs to. Must be a {@link AbstractModelMessage}.
     * @param text The text content.
     * @param thoughtSignature The signature of the thought process as a byte array.
     * @param thought Whether this part represents a thought process.
     */
    ModelTextPart(AbstractModelMessage message, String text, byte[] thoughtSignature, boolean thought) {
        super(message, text);
        this.thoughtSignature = thoughtSignature;
        this.thought = thought;
        
        // Initialize expanded state for thoughts based on config. 
        if (thought) {
            setExpanded(getChatConfig().isExpandThoughts());
        }
        
        // Leaf class publication
        message.addPart(this);
    }

    @Override
    public boolean isThought() {
        return thought;
    }

    /**
     * {@inheritDoc}
     * Returns the default maximum depth for thoughts if this is a thought part,
     * otherwise falls back to the standard text part depth.
     */
    @Override
    protected int getDefaultMaxDepth() {
        if (isThought()) {
            return getChatConfig().getDefaultThoughtPartMaxDepth();
        }
        return super.getDefaultMaxDepth();
    }

    
    /**
     * {@inheritDoc}
     * Internal model thoughts are surgically removable when expired, 
     * even if their parent message is still active.
     */
    @Override
    public boolean isGarbageCollectable() {
        if (isThought()) {
            return isEffectivelyPruned();
        }
        return super.isGarbageCollectable();
    }
}
