/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.ai.model.core;

import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;

/**
 * A specialized {@link BlobPart} for binary content generated by the model,
 * including internal thought process details.
 *
 * @author anahata-ai
 */
@Getter
@Setter
public class ModelBlobPart extends BlobPart implements ThoughtSignature {

    private byte[] thoughtSignature;

    /**
     * Constructs a ModelBlobPart from raw byte data and a specified MIME type.
     *
     * @param message The model message this part belongs to. Must be a {@link AbstractModelMessage}.
     * @param mimeType The MIME type.
     * @param data The binary data.
     * @param thoughtSignature The signature of the thought process as a byte array.
     */
    public ModelBlobPart(@NonNull AbstractModelMessage message, @NonNull String mimeType, @NonNull byte[] data, byte[] thoughtSignature) {
        super(message, mimeType, data);
        this.thoughtSignature = thoughtSignature;
    }
}